### PR TITLE
Django 1.9 support

### PR DESCRIPTION
**Pull request by hellysmile**

### CODE REVIEW

**Comment by ntucker** [comment]
+1

**Comment by joshowen** [comment]
+1

**Comment by inferno001** [comment]
+1

**Comment by freyley** [comment]
+1

**Comment by AyumuKasuga** [comment]
+1

**Comment by FZambia** [comment]
+1

**Comment by grey0ne** [comment]
+1

**Comment by MiddleFork** [comment]
+1 anytime....

**Comment by joshowen** [comment]
@stefanw any reason not to merge this?

**Comment by stefanw** [comment]
I had to fix a couple of more things for Django 1.9 compatibility, but `develop` should work now. A release 0.10 is out, please check it out and report.

**Comment by joshowen** [comment]
Thanks!

**Pull request merged**
